apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: {{ .Values.metadata.namespace }}
spec:
  selector:
    app: sonarr
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 8989
  type: ClusterIP
