apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: servarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - name: radarr
        image: linuxserver/radarr:latest
        ports:
        - containerPort: 7878
        volumeMounts:
        - name: config
          mountPath: /config
        - name: downloaded-media
          mountPath: /data
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/New_York"
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: radarr-config
      - name: downloaded-media
        persistentVolumeClaim:
          claimName: {{ .Values.global.media_volume }}
