apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: {{ .Values.metadata.namespace }}
spec:
  selector:
    app: sabnzbd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7878 
  type: ClusterIP
