apiVersion: v1
kind: ConfigMap
metadata:
  name: gluetun-iptables-post-rules
  namespace: servarr
data:
  post-rules.txt: |
    iptables -A INPUT -i eth0 -s 0.0.0.0/0 -d 192.168.2.0/24 -p udp --sport 1197 -j ACCEPT
    iptables -A INPUT -i eth0 -s 0.0.0.0/0 -d 192.168.2.0/24 -p tcp --sport 1197 -j ACCEPT
   