# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: sabnzbd-config
#   namespace: servarr
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: sabnzbd-downloads
#   namespace: servarr
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: {{ .Values.pvc.download_size }}


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-movies
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-series
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi