apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: n8n
type: Opaque
data:
  POSTGRES_DB: cHNfZGI=         # base64 of “ps_db”
  POSTGRES_USER: cHNfdXNlcg==   # base64 of “ps_user”
  POSTGRES_PASSWORD: U2VjdXJlUGFzc3dvcmQ=  # base64 of “SecurePassword”

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  namespace: n8n
spec:
  storageClassName: <your-storageclass>
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: n8n
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: postgres-credentials
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresdata
        readinessProbe:
          exec:
            command:
              - pg_isready
              - -U
              - "$(POSTGRES_USER)"
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: postgresdata
        persistentVolumeClaim:
          claimName: postgres-volume-claim

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: n8n
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
