apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvclaim
  namespace: n8n
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: n8n
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: postgres-credentials
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresdata
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - "pg_isready -U $POSTGRES_USER"
      volumes:
      - name: postgresdata
        persistentVolumeClaim:
          claimName: postgres-pvclaim

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: n8n
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5678
      targetPort: 5432
  selector:
    app: postgres
