apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-storage-shared-with-jellyfin
  namespace: opencloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-cloud
