apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.global.media_volume }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-cloud 
