apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: {{ .Values.metadata.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      containers:
        - name: gluetun
 
          image: ghcr.io/qdm12/gluetun:latest
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          ports:
            - containerPort: 9091
          env:
            - name: VPN_SERVICE_PROVIDER
              value: "protonvpn"
            - name: DNS_ADDRESS
              value: 1.1.1.1
            - name: OPENVPN_USER
              valueFrom:
                secretKeyRef:
                  name: sabnzbd-secret
                  key: openvpnUsername
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sabnzbd-secret
                  key: openvpnPassword
            - name: FIREWALL_INPUT_PORTS
              value: 8080,9091
        - name: sabnzbd
          image: linuxserver/sabnzbd:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /config
      initContainers:
        - name: init-sabnzbd-config
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "__version__ = 19" > /config/sabnzbd.ini
              echo "__encoding__ = utf-8" >> /config/sabnzbd.ini
              echo "[misc]" >> /config/sabnzbd.ini
              echo "api_key = $APIKEY" >> /config/sabnzbd.ini
              cat /config/sabnzbd-configmap.ini >> /config/sabnzbd.ini
              echo "password = $PASSWORD" >> /config/sabnzbd.ini
              echo "username = $USERNAME" >> /config/sabnzbd.ini
          env:
            - name: APIKEY
              valueFrom:
                secretKeyRef:
                  name: sabnzbd-secret
                  key: apiKey
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: sabnzbd-secret
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sabnzbd-secret
                  key: password
          volumeMounts:
            - name: config
              mountPath: /config
            - name: sabnzbd-configmap
              mountPath: /config/sabnzbd-configmap.ini
              subPath: sabnzbd.ini
      volumes:
        - name: config
          emptyDir: {}
        - name: sabnzbd-configmap
          configMap:
            name: sabnzbd-configmap