apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: {{ .Values.metadata.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      containers:
        - name: sabnzbd
          image: linuxserver/sabnzbd:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /config
        # Add other volumeMounts here
      initContainers:
        - name: init-sabnzbd-config
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "__version__ = 19" > /config/sabnzbd.ini
              echo "[misc]" >> /config/sabnzbd.ini
              echo "username = $USERNAME" >> /config/sabnzbd.ini
              echo "password = $PASSWORD" >> /config/sabnzbd.ini
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: sabnzbd-secret
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sabnzbd-secret
                  key: password
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          emptyDir: {}
