apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: {{ .Values.metadata.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      containers:
        - name: sabnzbd
          image: linuxserver/sabnzbd:latest
          ports:
            - containerPort: 8080
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "UTC"
            - name: SABNZBD_HOSTNAME
              value: "sabnzbd.mydomain.com"  # Replace with your actual domain
          volumeMounts:
           - name: config
             mountPath: /config
           - name: downloads
             mountPath: /downloads
            # - name: sabnzbd-configmap
            #   mountPath: /config/sabnzbd.ini
            #   subPath: sabnzbd.ini
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: sabnzbd-config
        - name: downloads
          persistentVolumeClaim:
            claimName: sabnzbd-downloads
        # - name: sabnzbd-configmap
        #   configMap:
        #     name: sabnzbd-configmap

