---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sabnzbd-secret
  namespace: servarr
spec:
  encryptedData:
    apiKey: AgCB268FT+ftQgrHJHj2JbS1Ss5bFoOEVPv5fvIKZYd5Q1V4gMIj/V2CrP2/R/pn5FIIMDSYgBZ5v5mGnfHtJ9EUviLZAUeJFoTMdyA1eBNbPaosCTaYeKQHBpt7OdO8kIlDLOtjm08Prknyiv4Xsf0xDOtuaNh4bVoO0iw7Jcj5HaBb2p8jGbtsUOHHJKXFoLL08+Jq9Jl2QeYerrzENU4+fAJ36/nQdLeZbiK1SFT2IsdRQpWl+EuMxKC1ZLH31GjLLGxBNwm4VrzRjUIuZIVzf/zvL59C3zpDsOYcNFkQKfEnE6bnULEXao3lIZq8DPS+nPnf9LNv+m/eemWwqeXCfUx2h063DLM4M/9X6lvyWuKgUr2fV5KX3OSUbJIADH9R7CQcfzZ4dlPsVmv065CFQvjIatdHMg2h8uW14UWFkntg3UROr+UDV/GblCMc8ryNv4INyfUiNGfd+FxSwrK4aBg97q6Z4UkHJ5hNvc3xmW6LRFQUqoYhYLr5Xp/0Wndi/Lh7whGKgWhi/rv+8E5aeH8B6FIcuHBGwak/WY/GyMiZZem3TWf1kMR+HagJ6tGZAwpaJLNFcgza4CR+Zm7olGblgxMfD3eTEAhB9LxvYoOz+spO+JmlebxQH0AaCBOjzQ83jeR0uxpiivt/4u6pupppo2COD6zr7GWnGyFXVc0hP4ZBrhbVk3bsXUk8Aen/37nivcj5bn3d
    password: AgAvZporoehM1EOOk650Era+bhmf/S9wfDg06/O3vabRi+yGAiBEAyQr+HxH0KfO+IbeYz940xRezssE2Qa3cE/WnKP7j2+XgeAgQL2XACOmRPcDGJ+UVJNXX+fwZWZzzgBX0JXB6JHrof0IUlUOV6dGg+6XBa8up7qPp017gSn2u1kQose1g/YiMcn7wF2JJ9H7VLZl0UdvUMTg7a2cRQ39gszPNIehfgEJew38+AjF/Gt6jnFOeXnBgUDrqmrDPoyePHyQ5RkrTUmnWIWOHyrnfpNQn8VxMRSYAAXAzY4YJSORgS3NOwcZN2RGku74OLIYRj/TmW+sAyoejfT53zXiIXrcgHnujAlrzbMWKA6ZUEKSQGP7rqv39G1hot/75YG8KAHJcd4+PMztIf9WyuWWzOB3Txg0H1CBWtS5x1Mt/S98cX7XBGQ1TvyZ3USsvGpd+9XMeQG85yJj8etd0/7LMb6j/rONKRiFFKl6zJg+qqq9xP+iP4K2qygSy6Qfm7jFmjweVGbbYTl4mW/ldO3+mOtYGBwZejySJKKQRIPa2FpeBlvY/HlY/qgtlkyrKboTrsB+d7zdPmCvtrtk4tY/+wjwOZ8aG0WHjedAl4wA4IkwNET7qRrh3mVhDoEWTV80jqJqDqdRS2eOtgssYkQcVFeuQY3ty/Vns6PyIzWkDQ5qFOsjHrv0dVqkn7QtUjvBjbrN7AGrQQ==
  template:
    metadata:
      creationTimestamp: null
      name: sabnzbd-secret
      namespace: servarr
    type: Opaque
