---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    apiKey: AgBYPPMFsSbOxl8PnAbY4rZkK+dPv6Yx5iRVsFVe4WYGdlkPTH36IdLQXX0Sh9dz0U9K+LdaQls0P+jnAQJL86Y7FSWDWJRvTC10HHfjTM+AhbIaPoJzli1VbXhMh1bVEKyUQ/oUEf78hzpUf4Cz0Vxq7rXJ0N02lKpV9rkeuwr2mXl3cX+9vh6EIVKO/7vUAuXBAqICIwb/9Ld9a8avAEo62gTfmzcnJLuaO5BnCgAMJCIMzn5QZ1hdcB0UOxsegDybKSBd+BPnysZZMh6kD9IxbFftUGAnlcVGRItsvHdvW2eXNwrSRB5165b2LbtBDJt9zFk2afuvYYZkJTz81n1mxv3ZCw+ThfGFj17LcW3IkAQna+hjm6wq+C8Fyyx1FEGb2QT5eUfSchAjx94+OV7dC08grJ/URiNiShEtym+dGF0lWXL/7Lg+DvPF2dvxbJYOvmrubqojvxMvpfA0QETosaSOc4iaUyyWDTs7PEAii4SMEFFr3SGLnYvDNsjGZDGul1riTPB7YrpsFeCIXHAnpU5u9AYUIFEnxA+uucrzY3fo1tznI5vjCHqEJSRE46Xs0LEAAjBjRjMcWabBTyRl81jeeyk6pHsmM9KTt6Uozl1B+1OyKw00eO/SvmORareKkXyLmeC4++Y98tGwPSAFtp3Too7tLUgyo5TuO7p2lzWdDI8tVFHfLPF4f26FSoA31s9hwdAu5IkC
    password: AgAkVnLqbJyZx8kLmVsGeCrMHUzFE1h9O6PCHwisD0II0qe/bCzbwqIxbahegHs4JOcnByrFqwiMI7EqaD3GTC4lvWsq0iaAPRsQLTQsuFLi8YwqCiCfjss95EbB2Zt3vZx0TVh4iYzpUeBBcsesNo3ycSAkXaBGqT93cKOt5wRuejnmJRf2jqoZcFUPwJIA9MK2G9Cmhm3m6N+hGV9T6Ygo27G52HkzRzO9aOS5SithcS8CDyh+4we3jnMaOKWRF4yBpv6765b/suihuTa0PrR889udgGRIdkd2cdbHhPCeNMaHuc2wrdDSFsLRwWwloOOGlgW4ZOTrd1mQelwCgzhg9TM7HBn9+N0K1B22KzKaoOQY8Ix1j8yI/X2SktTgyITL2zQ4frwN2dhcOvbMjfANcsLDrYj7COnKw2Aa4sX8SrZU/EsqFGY4BKXLLbKehM4p/iDW0WZfDeTtgdcahnuJZCyaIG5vxkbkTu4qana4XBLN4kwD7xWkjHuNRP70zgZbEyhsk8B0TCHQ/YFK9x5DUpPV4rSr7EZHRMCsqm1AQzJ+yW72wqkUssqJ+WksUg5A+nScuSfURdZT9lfVtzEGHZUn6GnSXyBBoclWMt7fHmwUZ11CTRBCOqfkadHTGrGKLG57t83uAEyjIimrZp4GPbu8b4x8xJQCrSnvYaHU2LHRPKXZNub09+7cibr6yTSiU7mvzvoGQQ==
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
    type: Opaque
