apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: {{ .Values.metadata.namespace }}
spec:
  selector:
    app: radarr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9696  
  type: ClusterIP
