# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: sonarr
#   namespace: servarr
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: sonarr
#   template:
#     metadata:
#       labels:
#         app: sonarr
#     spec:
#       containers:
#       - name: sonarr
#         image: linuxserver/sonarr:latest
#         ports:
#         - containerPort: 8989
#         volumeMounts:
#         - name: config
#           mountPath: /config
#         - name: downloaded-media
#           mountPath: /data
#         env:
#         - name: PUID
#           value: "1000"
#         - name: PGID
#           value: "1000"
#         - name: TZ
#           value: "America/New_York"
#       volumes:
#       - name: config
#         persistentVolumeClaim:
#           claimName: longhorn-sonarr-config
#       - name: downloaded-media
#         persistentVolumeClaim:
#           claimName: {{ .Values.global.media_volume }}
