apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: servarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - name: sonarr
        image: linuxserver/sonarr:latest
        ports:
        - containerPort: 8989
        volumeMounts:
        - name: config
          mountPath: /config
        - name: tv
          mountPath: /tv
        - name: downloads
          mountPath: /downloads
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/New_York"
      volumes:
      - name: config
        hostPath:
          path: /data/sonarr/config
          type: DirectoryOrCreate
      - name: tv
        hostPath:
          path: /data/sonarr/tv
          type: DirectoryOrCreate
      - name: downloads
        hostPath:
          path: /data/sonarr/downloads
          type: DirectoryOrCreate
