apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opencloud-ingress-opencloud
  namespace: opencloud
  # annotations:
  #   cert-manager.io/cluster-issuer: "global-cluster-issuer"
spec:
  ingressClassName: nginx
  rules:
    - host: opencloud.jonelli.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: opencloud-service
                port:
                  number: 443
  tls:
    - hosts:
        - opencloud.jonelli.uk
      secretName: opencloud-tls-secret