apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: global-cluster-issuer
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  acme:
    email: jonasbauerwi@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cluster-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: jonasbauerwi@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token