apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: nginx
spec:
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: nginx
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: main
    path: gitops/ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true