apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-helmchart
  namespace: argocd
spec:
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: ingress-nginx
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: "3.7.1"  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true