apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: ingress-nginx
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx  
    chart: ingress-nginx
    targetRevision: "3.7.1"  
    helm:
      values: |
        controller:
          service:
            externalIPs:
              - "<EXTERNAL_IP>"  # Replace with your actual external IP or leave it blank
  syncPolicy:
    automated:
      prune: true
      selfHeal: true