apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
spec:
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: nginx-ingress
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: main
    path: ingress
    helm:
      values: |
        controller:
          service:
            type: LoadBalancer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
