apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    chart: cloudnative-pg
    targetRevision: 0.26.0 # Pick latest stable
  destination:
    namespace: cnpg-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n-helmchart
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  source:
    repoURL: oci://8gears.container-registry.com/library/n8n
    chart: n8n
    targetRevision: "1.0.0"
    helm:
      valueFiles:
        - ./../n8n_values.yaml
      # This tells ArgoCD/Helm to treat repoURL as OCI
      parameters:
        - name: "oci"
          value: "true"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
