apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
spec:
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: n8n
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: main
    path: n8n
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
