#Prod like set up with CloudNativePG and nginx-ingress
image:
  repository: n8nio/n8n
  tag: 1.81.4
imagePullSecrets:
  - name: 8gears-registry-n8n

main:
  config:
    db:
      type: postgresdb
      postgresdb:
        host: db-rw
        user: n8n
#        password: password is read from cnpg db-app secretKeyRef
        pool:
          size: 10
        ssl:
          enabled: false
          # reject_Unauthorized: true
          # ca_file: "/home/ssl/certs/postgresql/ca.crt"
  secret:
    n8n:
      encryption_key: "eV1yS6qYwDkaasehi5LfLH3NYEP8Di9ivYTRYeGznjk="

  extraEnv:
    DB_POSTGRESDB_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: db-app
          key: password
  # Mount the CNPG CA Cert into N8N container
  extraVolumeMounts:
    - name: db-ca-cert
      mountPath: /home/ssl/certs/postgresql
      readOnly: true

  extraVolumes:
    - name: db-ca-cert
      secret:
        secretName: db-ca
        items:
          - key: ca.crt
            path: ca.crt
  resources:
    limits:
      memory: 2048Mi
    requests:
      memory: 512Mi

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: global-cluster-issuer-dev
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: n8n.jonelli.uk
      paths:
        - /
  tls:
    - secretName: n8n-ingress-tls
      hosts:
        - n8n.jonelli.uk
