apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: servarr
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
--- 
apiVersion: v1
kind: Namespace
metadata:
  name: opencloud
  annotations:
    argocd.argoproj.io/sync-wave: "-1"