apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud-aio
  namespace: argocd
spec:
  project: default

  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: nextcloud

  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: main
    path: nextcloud

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
