apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud2
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud2

  source:
    repoURL: https://nextcloud.github.io/helm/
    chart: nextcloud                
    targetRevision: 8.7.0                       
    helm:
      releaseName: nextcloud
      values: |
        nextcloud:
          host: nextcloud.jonelli.uk
          username: admin
          password: changeme

        image:
          registry: docker.io
          repository: library/nextcloud
          flavor: apache
          tag: latest

        internalDatabase:
          enabled: true

        persistence:
          enabled: true
          size: 8Gi

        service:
          type: ClusterIP
          port: 8080

        ingress:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
