apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: servarr
  namespace: argocd
spec:
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: servarr
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: main
    path: opencloud/helm/opencloud-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
