apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencloud
  namespace: argocd
spec:
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: opencloud
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: main
    path: opencloud/helm/charts/opencloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
