apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: argocd
spec:
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: radarr
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: main
    path: radarr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
