apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-helmchart
  namespace: argocd
spec:
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: kube-system
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: "0.29.0"
    helm:
      values: |
        fullnameOverride=sealed-secrets-controller
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
