apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: servarr
  namespace: argocd
spec:
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: nginx-ingress
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: main
    path: sabnzbd_prowlarr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
