apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ingress
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: git@github.com:jbauer12/gitopshomeserver.git
    targetRevision: main
    path: gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true