apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: servarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
      - name: prowlarr
        image: linuxserver/prowlarr:latest
        ports:
        - containerPort: 9696
        volumeMounts:
        - name: config
          mountPath: /config
        - name: downloads
          mountPath: /downloads
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/New_York"
      volumes:
      - name: config
        hostPath:
          path: /data/prowlarr/config
          type: DirectoryOrCreate
      - name: downloads
        hostPath:
          path: /data/prowlarr/downloads
          type: DirectoryOrCreate
