apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sabnzbd-ingress
  namespace: {{ .Values.metadata.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: "global-cluster-issuer"
spec:
  ingressClassName: nginx
  rules:
  - host: sabnzbd.jonelli.uk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sabnzbd
            port:
              number: 80
  tls:
    - hosts:
        - sabnzbd.jonelli.uk
      secretName: sabnzbd-tls-secret

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prowlarr-ingress
  namespace: {{ .Values.metadata.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: "global-cluster-issuer"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
    - host: prowlarr.jonelli.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prowlarr
                port:
                  number: 80
  tls:
    - hosts:
        - prowlarr.jonelli.uk
      secretName: prowlarr-tls-secret
