
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  namespace: {{ .Values.metadata.namespace }}
spec:
  selector:
    app: sabnzbd
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 8080   
  type: ClusterIP      
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: {{ .Values.metadata.namespace }}
spec:
  selector:
    app: prowlarr
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 9696  
  type: ClusterIP

