apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: servarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      initContainers:
      - name: fix-permissions
        image: busybox
        securityContext:
          runAsUser: 0
        command: ["sh", "-c", "chown -R 1000:1000 /config"]
        volumeMounts:
        - name: config
          mountPath: /config
      containers:
      - name: jellyfin
        image: linuxserver/jellyfin:latest
        ports:
        - containerPort: 8096
        volumeMounts:
        - name: config
          mountPath: /config
        - name: downloaded-media
          mountPath: /data
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/New_York"
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: jellyfin-config-rwx
      - name: downloaded-media
        persistentVolumeClaim:
          claimName: {{ .Values.global.media_volume }}