apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: servarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
      - name: jellyfin
        image: linuxserver/jellyfin:latest
        ports:
        - containerPort: 8096
        volumeMounts:
        - name: config
          mountPath: /
        - name: downloaded-media
          mountPath: /media
        # env:
        # - name: PUID
        #   value: "1000"
        # - name: PGID
        #   value: "1000"
        # - name: TZ
        #   value: "America/New_York"
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: jellyfin-config
      - name: downloaded-media
        persistentVolumeClaim:
          claimName: {{ .Values.global.media_volume }}