apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: conf-jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-storage-jellyfin
  namespace: servarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 99Gi
  storageClassName: nfs-cloud


