apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-jellyfin-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi