apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-opencloud-opencloud-posixfs
  namespace: servarr
spec:
  accessModes:
    - ReadWriteMany    # must match the PV
  resources:
    requests:
      storage: 10Gi    # must be <= PV size
  volumeName: cloud-opencloud-opencloud-posixfs  # exact PV name
  storageClassName: ""       # important: no storageClass, otherwise provisioner makes a new dir


