apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: {{ .Values.metadata.namespace }}
spec:
  selector:
    app: sabnzbd
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 9696  
  type: ClusterIP