metadata:
  namespace: servarr

global:
  movie_volume: downloaded-movies
  series_volume: downloaded-series
  prowlarr_volume: prowlarr-downloads

service:
  port: 80 

# radarr:

# sonarr:

# sabnzbd_prowlarr: 